name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: >-
          sudo apt-get install -y
          texlive-latex-extra
          texlive-fonts-recommended
          texlive-fonts-extra
          lmodern
          texlive-luatex
          texlive-xetex
          latexmk
      - uses: actions/checkout@v2
      - name: Download Figtree fonts
        run: |
          mkdir -p fonts
          wget -P fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Regular.ttf
          wget -P fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Italic.ttf
          wget -P fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Bold.ttf
          wget -P fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-BoldItalic.ttf
      - run: make poster.pdf
