name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: >
          sudo apt-get install -y
          texlive-latex-extra
          texlive-fonts-recommended
          texlive-fonts-extra
          lmodern
          texlive-luatex
          texlive-xetex
          latexmk
          fontconfig
      - name: Download Figtree fonts
        run: |
          mkdir -p figtree-fonts
          wget -P figtree-fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Regular.ttf
          wget -P figtree-fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Italic.ttf
          wget -P figtree-fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-Bold.ttf
          wget -P figtree-fonts https://raw.githubusercontent.com/erikdkennedy/figtree/master/fonts/ttf/Figtree-BoldItalic.ttf
      - name: Install fonts in shared font directory
        run: |
          sudo mkdir -p /usr/share/fonts/truetype/figtree
          sudo cp figtree-fonts/*.ttf /usr/share/fonts/truetype/figtree/
          sudo fc-cache -f -v
      - uses: actions/checkout@v2
      - run: make poster.pdf
